version: 2.0

variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

jobs:
  dependencies:
    docker:
      - image: node:12.16.1
    steps:
      - checkout
      - run: npm ci
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
            - cache/Cypress

  build:app:
    docker:
      - image: node:12.16.1
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run: npm ci
      - run: npm run build

  test:unit:
    docker:
      - image: node:12.16.1
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run: npm ci
      - run: npm run test:unit:coverage
      - store_test_results:
          path: coverage/clover.xml

  build:docker:
    docker:
      - image: docker:stable
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t web .

workflows:
  version: 2
  build:
    jobs:
      - dependencies
      - build:app:
          requires:
            - dependencies
      - test:unit:
          requires:
            - build:app
      - build:docker:
          requires:
            - test:unit
